DEPLOY-2 #14

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -60,9 +60,14 @@ jobs:
 
             # Crear .env.PROD BACK laravel-api
             cd ./back/laravel-api
-            ls -a
             echo "Copiant .env.PROD de Back laravel-api..."
             cp .env.PROD .env
+            if [ -f .env ]; then
+              echo "El fitxer s'ha creat correctament, afegint variables..."
+            else
+              echo "Error: No s'ha creat el fitxer .env, no es poden afegir variables"
+              exit 1
+            fi
             echo "DB_CONNECTION=pgsql" >> .env
             echo "DB_HOST=pfg1-postgres" >> .env
             echo "DB_PORT=5432" >> .env
